runtime: go
api_version: go1

handlers:
# Static assets
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always
- url: /js
  static_dir: static/js
  secure: always
- url: /css
  static_dir: static/css
  secure: always
- url: /images
  static_dir: static/images
  secure: always
- url: /game
  static_files: static/game.html
  upload: static/game\.html
  secure: always
- url: /
  static_files: static/main.html
  upload: static/main\.html
  secure: always

# Even though there's catch all routing, without these two lines
# endpoints is not going to work.
- url: /_ah/spi/.*
  script: _go_app
